site_name: "Ostorlab."
site_description: "Ostorlab is an open-source project to help automate security testing. Ostorlab standardizes interoperability between tools in a consistent, scalable, and performant way."
site_url: "https://docs.ostorlab.io"
#repo_url: "https://github.com/Ostorlab/ostorlab"
repo_name: "Ostorlab/ostorlab"
copyright: 'Copyright &copy; 2021 Ostorlab.'
edit_uri: ""
nav:
  - Home: index.md
#  - Tutorials:
#    - tutorials/run-your-first-scan.md
  - Guide:
      - Getting Started: guide/README.md
      - Remediation: remediation/README.md
      - Analysis: ide/README.md
      - API: api/README.md
      - User management: user_management/README.md
      - Product:  product/README.md
#      - Knowledge Base: kb/README.md #to import
      - Compliance: compliance/README.md
      - Enterprise: enterprise/README.md

    #  this one is only a demo
  #  - API Reference: SDK/README.md
  - Changelog: changelog/README.md
  - FAQ: faq/README.md
  - Privacy: privacy/README.md
  - Terms: terms/README.md

plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
       on_pre_build: "docs.hooks:generate_kb"
  - mkdocstrings:
      watch:
        - ../src/ostorlab

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: "material"
  favicon: /public/Ostorlab-sm.png
  logo: "https://www.ostorlab.co/img/logo/logo-emblem.png"
  custom_dir: docs/overrides
  features:
  - navigation.tabs
  - tabs
  - instant
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: UA-61939785-1
